### ISSUE TITLE
Missing GTK Libraries

### ISSUE THREAD

**Issue by mrnra** [blueOkiris/clonger#2]
After installing and running current release on Windows 10 (tried with both x64 and x86), command prompt prints "Welcome to clonger!" followed by this exception: 

Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Clonger.Presentation.Program.Main()

**Comment by blueOkiris** [comment]
I've thought a lot about this issue, and I have no idea how to fix it.
It's obviously been open a _long_ time, but I didn't forget about it.
This project kinda died (i.e. I stopped working on it), but I think I'm gonna pick it up again.

**I plan to do a bit of an overhaul** based on feedback I've received from various places like r/conlangs and its discord.
I also plan to use Rust to do it in the new version (currently, it uses C# and .NET). The rust version will likely no longer require a Gtk dll like the C# one did (the origin of this issue).

If/when I complete the Rust version, which I currently plan to not require any kind of platform installed (like this one requires - .NET and .NET GTK), **I will probably close this issue then, as it will no longer be relevant.** Thanks for bringing up this important issue though

**Comment by blueOkiris** [comment]
I never really got far on the new version. I might still make the tool, but I'm planning to make it TUI only, not GUI, and a lot simpler. Closing this.
